<?php

return [
    'List' =>['ABDULLAH GÜL ÜNİVERSİTESİ',
        'ACIBADEM ÜNİVERSİTESİ',
        'ADANA BİLİM VE TEKNOLOJİ ÜNİVERSİTESİ',
        'ADIYAMAN ÜNİVERSİTESİ',
        'AFYON KOCATEPE ÜNİVERSİTESİ',
        'AFYONKARAHİSAR SAĞLIK BİLİMLERİ ÜNİVERSİTESİ',
        'AĞRI İBRAHİM ÇEÇEN ÜNİVERSİTESİ',
        'AKDENİZ ÜNİVERSİTESİ',
        'AKSARAY ÜNİVERSİTESİ',
        'ALANYA ALAADDİN KEYKUBAT ',
        'ALANYA HAMDULLAH EMİN PAŞA ÜNİVERSİTESİ',
        'ALTINBAŞ ÜNİVERSİTESİ',
        'AMASYA ÜNİVERSİTESİ',
        'ANADOLU ÜNİVERSİTESİ',
        'ANKA TEKNOLOJİ ÜNİVERSİTESİ',
        'ANKARA HACI BAYRAM VELİ ÜNİVERSİTESİ',
        'ANKARA SOSYAL BİLİMLER ÜNİVERSİTESİ',
        'ANKARA ÜNİVERSİTESİ',
        'ANKARA YILDIRIM BEYAZIT ÜNİVERSİTESİ',
        'ANTALYA AKEV ÜNİVERSİTESİ',
        'ARDAHAN ÜNİVERSİTESİ',
        'ARTVİN ÇORUH ÜNİVERSİTESİ',
        'ATAŞEHİR ADIGÜZEL MESLEK YÜKSEKOKULU',
        'ATATÜRK ÜNİVERSİTESİ',
        'ATILIM ÜNİVERSİTESİ',
        'AVRASYA ÜNİVERSİTESİ',
        'BAHÇEŞEHİR ÜNİVERSİTESİ',
        'BALIKESİR ÜNİVERSİTESİ',
        'BARTIN ÜNİVERSİTESİ',
        'BAŞKENT ÜNİVERSİTESİ',
        'BATMAN ÜNİVERSİTESİ',
        'BAYBURT ÜNİVERSİTESİ',
        'BEYKENT ÜNİVERSİTESİ',
        'BEYKOZ ÜNİVERSİTESİ',
        'BEZM-İ ÂLEM VAKIF ÜNİVERSİTESİ',
        'BİLECİK ŞEYH EDEBALİ ÜNİVERSİTESİ',
        'BİNGÖL ÜNİVERSİTESİ',
        'BİRİM ADI İNTERNET ADRESİ',
        'BİRİM ADI İNTERNET ADRESİ',
        'BİRUNİ ÜNİVERSİTESİ',
        'BİTLİS EREN ÜNİVERSİTESİ',
        'ÇANKIRI KARATEKİN ÜNİVERSİTESİ',
        'ÇUKUROVA ÜNİVERSİTESİ',
        'DİCLE ÜNİVERSİTESİ',
        'DOĞUŞ ÜNİVERSİTESİ',
        'DOKUZ EYLÜL ÜNİVERSİTESİ',
        'DÜZCE ÜNİVERSİTESİ',
        'EGE ÜNİVERSİTESİ',
        'ERCİYES ÜNİVERSİTESİ',
        'ERZİNCAN BİNALİ YILDIRIM ÜNİVERSİTESİ',
        'ERZURUM TEKNİK ÜNİVERSİTESİ',
        'ESKİŞEHİR OSMANGAZİ ÜNİVERSİTESİ',
        'ESKİŞEHİR TEKNİK ÜNİVERSİTESİ',
        'FARUK SARAÇ TASARIM MESLEK YÜKSEKOKULU',
        'FENERBAHÇE ÜNİVERSİTESİ',
        'GALATASARAY ÜNİVERSİTESİ',
        'GAZİ ÜNİVERSİTESİ',
        'GAZİANTEP BİLİM VE TEKNOLOJİ ÜNİVERSİTESİ',
        'GEBZE TEKNİK ÜNİVERSİTESİ',
        'GİRESUN ÜNİVERSİTESİ',
        'GÜMÜŞHANE ÜNİVERSİTESİ',
        'HACETTEPE ÜNİVERSİTESİ',
        'HAKKARİ ÜNİVERSİTESİ',
        'HALİÇ ÜNİVERSİTESİ',
        'HARRAN ÜNİVERSİTESİ',
        'HASAN KALYONCU ÜNİVERSİTESİ',
        'HATAY MUSTAFA KEMAL ÜNİVERSİTESİ',
        'HİTİT ÜNİVERSİTESİ',
        'İBN HALDUN ÜNİVERSİTESİ',
        'IĞDIR ÜNİVERSİTESİ',
        'İHSAN DOĞRAMACI BİLKENT ÜNİVERSİTESİ',
        'İNÖNÜ ÜNİVERSİTESİ',
        'IŞIK ÜNİVERSİTESİ',
        'İSKENDERUN TEKNİK ÜNİVERSİTESİ',
        'ISPARTA UYGULAMALI BİLİMLER ÜNİVERSİTESİ',
        'İSTANBUL 29 MAYIS ÜNİVERSİTESİ',
        'İSTANBUL AREL ÜNİVERSİTESİ',
        'İSTANBUL ATLAS ÜNİVERSİTESİ',
        'İSTANBUL AYVANSARAY ÜNİVERSİTESİ',
        'İSTANBUL BİLGİ ÜNİVERSİTESİ',
        'İSTANBUL BİLİM ÜNİVERSİTESİ',
        'İSTANBUL ESENYURT ÜNİVERSİTESİ',
        'İSTANBUL GEDİK ÜNİVERSİTESİ',
        'İSTANBUL GELİŞİM ÜNİVERSİTESİ',
        'İSTANBUL KENT ÜNİVERSİTESİ',
        'İSTANBUL TİCARET ÜNİVERSİTESİ',
        'İSTANBUL ÜNİVERSİTESİ',
        'İSTANBUL YENİ YÜZYIL ÜNİVERSİTESİ',
        'İSTİNYE ÜNİVERSİTESİ',
        'İZMİR BAKIRÇAY ÜNİVERSİTESİ',
        'İZMİR DEMOKRASİ ÜNİVERSİTESİ',
        'İZMİR EKONOMİ ÜNİVERSİTESİ',
        'İZMİR KATİP ÇELEBİ ÜNİVERSİTESİ',
        'KADİR HAS ÜNİVERSİTESİ',
        'KAFKAS ÜNİVERSİTESİ',
        'KAHRAMANMARAŞ İSTİKLAL ÜNİVERSİTESİ',
        'KAPADOKYA ÜNİVERSİTESİ',
        'KARABÜK ÜNİVERSİTESİ',
        'KARADENİZ TEKNİK ÜNİVERSİTESİ',
        'KARAMANOĞLU MEHMETBEY ÜNİVERSİTESİ',
        'KASTAMONU ÜNİVERSİTESİ',
        'KAYSERİ ÜNİVERSİTESİ',
        'KİLİS 7 ARALIK ÜNİVERSİTESİ',
        'KIRKLARELİ ÜNİVERSİTESİ',
        'KIRŞEHİR AHİ EVRAN ÜNİVERSİTESİ',
        'KOÇ ÜNİVERSİTESİ',
        'KOCAELİ ÜNİVERSİTESİ',
        'KONYA GIDA VE TARIM ÜNİVERSİTESİ',
        'KONYA TEKNİK ÜNİVERSİTESİ',
        'KTO KARATAY ÜNİVERSİTESİ',
        'KÜTAHYA DUMLUPINAR ÜNİVERSİTESİ',
        'KÜTAHYA SAĞLIK BİLİMLERİ ÜNİVERSİTESİ',
        'LOKMAN HEKİM ÜNİVERSİTESİ',
        'MANİSA CELÂL BAYAR ÜNİVERSİTESİ',
        'MARDİN ARTUKLU ÜNİVERSİTESİ',
        'MARMARA ÜNİVERSİTESİ',
        'MEF ÜNİVERSİTESİ',
        'MERSİN ÜNİVERSİTESİ',
        'MİMAR SİNAN GÜZEL SANATLAR ÜNİVERSİTESİ',
        'MUĞLA SITKI KOÇMAN ÜNİVERSİTESİ',
        'MUNZUR ÜNİVERSİTESİ',
        'MUŞ ALPARSLAN ÜNİVERSİTESİ',
        'NECMETTİN ERBAKAN ÜNİVERSİTESİ',
        'NEVŞEHİR HACI BEKTAŞ VELİ ÜNİVERSİTESİ',
        'NİĞDE ÖMER HALİSDEMİR ÜNİVERSİTESİ',
        'NİŞANTAŞI ÜNİVERSİTESİ',
        'NUH NACİ YAZGAN ÜNİVERSİTESİ',
        'ONDOKUZ MAYIS ÜNİVERSİTESİ',
        'ORDU ÜNİVERSİTESİ',
        'ORTA DOĞU TEKNİK ÜNİVERSİTESİ',
        'OSMANİYE KORKUT ATA ÜNİVERSİTESİ',
        'OSTİM TEKNİK ÜNİVERSİTESİ',
        'ÖZYEĞİN ÜNİVERSİTESİ',
        'PAMUKKALE ÜNİVERSİTESİ',
        'PİRİ REİS ÜNİVERSİTESİ',
        'RECEP TAYYİP ERDOĞAN ÜNİVERSİTESİ',
        'SABANCI ÜNİVERSİTESİ',
        'SAĞLIK BİLİMLERİ ÜNİVERSİTESİ',
        'SAKARYA UYGULAMALI BİLİMLER ÜNİVERSİTESİ',
        'SAMSUN ÜNİVERSİTESİ',
        'SELÇUK ÜNİVERSİTESİ',
        'SEMERKAND BİLİM VE MEDENİYET ÜNİVERSİTESİ',
        'SİNOP ÜNİVERSİTESİ',
        'ŞIRNAK ÜNİVERSİTESİ',
        'SİVAS BİLİM VE TEKNOLOJİ ÜNİVERSİTESİ',
        'SÜLEYMAN DEMİREL ÜNİVERSİTESİ',
        'TARSUS ÜNİVERSİTESİ',
        'TED ÜNİVERSİTESİ',
        'TEKİRDAĞ NAMIK KEMAL ÜNİVERSİTESİ',
        'TOBB EKONOMİ VE TEKNOLOJİ ÜNİVERSİTESİ',
        'TOKAT GAZİOSMANPAŞA ÜNİVERSİTESİ',
        'TOROS ÜNİVERSİTESİ',
        'TRABZON ÜNİVERSİTESİ',
        'TRAKYA ÜNİVERSİTESİ',
        'TÜRK HAVA KURUMU ÜNİVERSİTESİ',
        'TÜRK-ALMAN ÜNİVERSİTESİ',
        'TÜRKİYE ULUSLARARASI İSLAM, BİLİM VE TEKNOLOJİ ÜNİVERSİTESİ',
        'UŞAK ÜNİVERSİTESİ',
        'ÜSKÜDAR ÜNİVERSİTESİ',
        'VAN YÜZÜNCÜ YIL ÜNİVERSİTESİ',
        'YALOVA ÜNİVERSİTESİ',
        'YAŞAR ÜNİVERSİTESİ',
        'YEDİTEPE ÜNİVERSİTESİ',
        'YILDIZ TEKNİK ÜNİVERSİTESİ',
        'YOZGAT BOZOK ÜNİVERSİTESİ',
        'YÜKSEK İHTİSAS ÜNİVERSİTESİ',
        'ZONGULDAK BÜLENT ECEVİT ÜNİVERSİTESİ'
    ],
]

?>
